/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package user;
import business.Consultant;
import data.ConsultantDB;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author icbt1
 */
public class ConsultantUI extends javax.swing.JFrame {
private DefaultTableModel tblModel;
private ConsultantDB cDB;
    /**
     * Creates new form ConsultantUI
     */
    public ConsultantUI() {
        initComponents();
        setLocationRelativeTo(this);
        tblModel=new DefaultTableModel();
        tblConsultant.setModel(tblModel);
        tblModel.addColumn("Consultant ID");
        tblModel.addColumn("First Name");
        tblModel.addColumn("Last Name");
        tblModel.addColumn("Category");
        tblModel.addColumn("Hospital");
        tblModel.addColumn("Telephone");
        
        cDB = new ConsultantDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConsultant = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCunsultantID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox();
        txtHospital = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        pnlAll = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultant = new javax.swing.JTable();

        setTitle("Consultant");
        setResizable(false);

        jLabel1.setText("Consultant ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Category");

        jLabel5.setText("Hospital");

        jLabel6.setText("Telephone");

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Eye Surgent", "ENT Surgent", "General Physician", "Cardiologist" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAll.setText("All");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultantLayout = new javax.swing.GroupLayout(pnlConsultant);
        pnlConsultant.setLayout(pnlConsultantLayout);
        pnlConsultantLayout.setHorizontalGroup(
            pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultantLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(pnlConsultantLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(btnAdd))))
                .addGroup(pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultantLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCunsultantID)
                            .addComponent(txtFirstName)
                            .addComponent(txtLastName)
                            .addComponent(cmbCategory, 0, 177, Short.MAX_VALUE)
                            .addComponent(txtHospital)
                            .addComponent(txtTelephone)))
                    .addGroup(pnlConsultantLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnFind)
                        .addGap(10, 10, 10)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlConsultantLayout.setVerticalGroup(
            pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultantLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCunsultantID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(pnlConsultantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnFind)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnAll))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tblConsultant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblConsultant);

        javax.swing.GroupLayout pnlAllLayout = new javax.swing.GroupLayout(pnlAll);
        pnlAll.setLayout(pnlAllLayout);
        pnlAllLayout.setHorizontalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAllLayout.setVerticalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlConsultant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlConsultant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        // Clear the table
    tblModel.setRowCount(0);

    // Retrieve all consultants from the database
    ArrayList<Consultant> cList = cDB.getAll();

    // If consultants are found, add them to the table
    if (cList != null) {
        for (Consultant c : cList) {
            tblModel.addRow(new Object[]{
                c.getcID(),
                c.getFirstName(),
                c.getLastName(),
                c.getCategory(),
                c.getHospital(),
                c.getTelephone()
            });
        }
    } else {
        JOptionPane.showMessageDialog(this, "No consultants found.");
    }

    }//GEN-LAST:event_btnAllActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Validate Consultant ID
    int consultantID;
    try {
        consultantID = Integer.parseInt(txtCunsultantID.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Consultant ID must be a number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate First Name and Last Name
    String firstName = txtFirstName.getText();
    String lastName = txtLastName.getText();
    if (firstName.isEmpty() || lastName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "First Name and Last Name are required.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate Category
    String category = cmbCategory.getSelectedItem().toString();
    if (category.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Category is required.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate Hospital
    String hospital = txtHospital.getText();
    if (hospital.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Hospital is required.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate Telephone
    String telephone = txtTelephone.getText();
    if (telephone.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Telephone number is required.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // If all inputs are valid, proceed to add the consultant
    Consultant c = new Consultant(consultantID, firstName, lastName, category, hospital, telephone);
    boolean flag = cDB.add(c);
    if (flag) {
        JOptionPane.showMessageDialog(pnlConsultant, "Consultant Added");
    } else {
        JOptionPane.showMessageDialog(pnlConsultant, "Consultant not Added");
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         // Validate Consultant ID
    int consultantID;
    try {
        consultantID = Integer.parseInt(txtCunsultantID.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Consultant ID must be a number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate First Name and Last Name
    String firstName = txtFirstName.getText();
    String lastName = txtLastName.getText();
    if (firstName.isEmpty() || lastName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "First Name and Last Name are required.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate Category
    String category = cmbCategory.getSelectedItem().toString();
    if (category.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Category is required.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate Hospital
    String hospital = txtHospital.getText();
    if (hospital.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Hospital is required.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate Telephone
    String telephone = txtTelephone.getText();
    if (telephone.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Telephone number is required.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // If all inputs are valid, proceed to update the consultant
    Consultant c = new Consultant(consultantID, firstName, lastName, category, hospital, telephone);
    boolean flag = cDB.update(c);
    if (flag) {
        JOptionPane.showMessageDialog(pnlConsultant, "Consultant Updated");
    } else {
        JOptionPane.showMessageDialog(pnlConsultant, "Consultant not Updated");
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
       // Validate Consultant ID
    int consultantID;
    try {
        consultantID = Integer.parseInt(JOptionPane.showInputDialog("Enter the Consultant ID"));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Consultant ID must be a number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Search for the consultant
    Consultant c = cDB.get(consultantID);
    if (c != null) {
        txtCunsultantID.setText(String.valueOf(c.getcID()));
        txtFirstName.setText(c.getFirstName());
        txtLastName.setText(c.getLastName());
        cmbCategory.setSelectedItem(c.getCategory());
        txtHospital.setText(c.getHospital());
        txtTelephone.setText(c.getTelephone());
    } else {
        JOptionPane.showMessageDialog(pnlConsultant, "The consultant record is not available");
    }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Get the consultant ID from the user
    int cID;
    try {
        cID = Integer.parseInt(JOptionPane.showInputDialog("Enter Consultant ID to delete:"));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Consultant ID must be a number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Delete the consultant from the database
    boolean success = cDB.delete(cID);

    // Show a message based on the result
    if (success) {
        JOptionPane.showMessageDialog(this, "Consultant deleted successfully!");
    } else {
        JOptionPane.showMessageDialog(this, "Failed to delete consultant.");
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultantUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAll;
    private javax.swing.JPanel pnlConsultant;
    private javax.swing.JTable tblConsultant;
    private javax.swing.JTextField txtCunsultantID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
