/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package user;

import javax.swing.JOptionPane;

/**
 *
 * @author icbt1
 */
public class MainUI extends javax.swing.JFrame {
private String userRole;

    /**
     * Creates new form MainUI
     */
    public MainUI(String userRole) {
        initComponents();
        setLocationRelativeTo(this);
        this.userRole = userRole;
        enforcePermissions(); // Enforce role-based permissions
    }

    // Method to enforce role-based permissions
    private void enforcePermissions() {
    // Only enable "New User" menu item for Managers
    if (!userRole.equals("Manager")) {
        mnuNewUser.setEnabled(false); // Disable "New User" menu item for non-Managers
        mnuDeleteUser.setEnabled(false); // Disable "Delete User" menu item
        mnuChangePassword.setEnabled(false); // Disable "Change Password" menu item
        mnuAddCashier.setEnabled(false);
    }

    // Disable other Manager-specific functionality for non-Managers
    if (userRole.equals("Cashier")) {
        mnuDeleteUser.setEnabled(false); // Disable "Delete User" menu item
        mnuChangePassword.setEnabled(false); // Disable "Change Password" menu item
        mnuAddCashier.setEnabled(false);
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuPatient = new javax.swing.JMenuItem();
        mnuBooking = new javax.swing.JMenuItem();
        mnuConsultant = new javax.swing.JMenuItem();
        mnuClose = new javax.swing.JMenuItem();
        JMenu2 = new javax.swing.JMenu();
        mnuHelp = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuLogOut = new javax.swing.JMenuItem();
        mnuChangePassword = new javax.swing.JMenuItem();
        mnuDeleteUser = new javax.swing.JMenuItem();
        mnuNewUser = new javax.swing.JMenuItem();
        mnuAddCashier = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        mnuPatient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuPatient.setText("Patient");
        mnuPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPatientActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPatient);

        mnuBooking.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuBooking.setText("Booking");
        mnuBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBookingActionPerformed(evt);
            }
        });
        jMenu1.add(mnuBooking);

        mnuConsultant.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuConsultant.setText("Consultant");
        mnuConsultant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultantActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsultant);

        mnuClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuClose.setText("Close");
        mnuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCloseActionPerformed(evt);
            }
        });
        jMenu1.add(mnuClose);

        jMenuBar1.add(jMenu1);

        JMenu2.setText("Help");
        JMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu2ActionPerformed(evt);
            }
        });

        mnuHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuHelp.setText("Help Section");
        mnuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelpActionPerformed(evt);
            }
        });
        JMenu2.add(mnuHelp);

        jMenuBar1.add(JMenu2);

        jMenu3.setText("Login");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        mnuLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuLogOut.setText("Logout");
        mnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogOutActionPerformed(evt);
            }
        });
        jMenu3.add(mnuLogOut);

        mnuChangePassword.setText("Change password");
        mnuChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChangePasswordActionPerformed(evt);
            }
        });
        jMenu3.add(mnuChangePassword);

        mnuDeleteUser.setText("Delete user");
        mnuDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteUserActionPerformed(evt);
            }
        });
        jMenu3.add(mnuDeleteUser);

        mnuNewUser.setText("New User");
        mnuNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewUserActionPerformed(evt);
            }
        });
        jMenu3.add(mnuNewUser);

        mnuAddCashier.setText("Add Cashier");
        mnuAddCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddCashierActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAddCashier);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuCloseActionPerformed

    private void mnuPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPatientActionPerformed
        // TODO add your handling code here:
        PatientUI pUI=new PatientUI();
        pUI.setVisible(true);
    }//GEN-LAST:event_mnuPatientActionPerformed

    private void mnuConsultantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultantActionPerformed
        // TODO add your handling code here:
        ConsultantUI cUI=new ConsultantUI();
        cUI.setVisible(true);
    }//GEN-LAST:event_mnuConsultantActionPerformed

    private void mnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogOutActionPerformed
        // TODO add your handling code here:
        LoginUI logUI=new LoginUI();
        logUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuLogOutActionPerformed

    private void mnuBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBookingActionPerformed
        // TODO add your handling code here:
        BookingUI bui=new BookingUI();
        bui.setVisible(true);
    }//GEN-LAST:event_mnuBookingActionPerformed

    private void JMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenu2ActionPerformed

    private void mnuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelpActionPerformed
        // TODO add your handling code here:
        HelpUI helpUI = new HelpUI(); // Create an instance of the HelpUI
        helpUI.setVisible(true); // Show the HelpUI window
    }//GEN-LAST:event_mnuHelpActionPerformed

    private void mnuNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewUserActionPerformed
        // TODO add your handling code here:
        NewUserUI newUserUI = new NewUserUI();
    newUserUI.setVisible(true);
    }//GEN-LAST:event_mnuNewUserActionPerformed

    private void mnuDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteUserActionPerformed
        if (userRole.equals("Manager")) {
        DeleteUserUI deleteUserUI = new DeleteUserUI();
        deleteUserUI.setVisible(true); // Show the DeleteUserUI window
    } else {
        JOptionPane.showMessageDialog(this, "Access Denied: Only Managers can delete users.");
    }
    }//GEN-LAST:event_mnuDeleteUserActionPerformed

    private void mnuChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChangePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuChangePasswordActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void mnuAddCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddCashierActionPerformed
        // TODO add your handling code here:
        if (userRole.equals("Manager")) {
        AddCashierUI addCashierUI = new AddCashierUI();
        addCashierUI.setVisible(true); // Show the AddCashierUI window
    } else {
        JOptionPane.showMessageDialog(this, "Access Denied: Only Managers can add Cashiers.");
    }
    }//GEN-LAST:event_mnuAddCashierActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Provide a default role for testing (e.g., "Manager" or "Cashier")
            new MainUI("Manager").setVisible(true); // Pass the role as an argument
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAddCashier;
    private javax.swing.JMenuItem mnuBooking;
    private javax.swing.JMenuItem mnuChangePassword;
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JMenuItem mnuConsultant;
    private javax.swing.JMenuItem mnuDeleteUser;
    private javax.swing.JMenuItem mnuHelp;
    private javax.swing.JMenuItem mnuLogOut;
    private javax.swing.JMenuItem mnuNewUser;
    private javax.swing.JMenuItem mnuPatient;
    // End of variables declaration//GEN-END:variables
}
